# Generated by Django 5.1.5 on 2025-01-23 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DateChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datechoice_text', models.DateField(verbose_name='date published')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.schedule')),
            ],
        ),
    ]
